## makeCacheMatrix and cacheSolve together return the inverse of a matrix, 
## if makeCacheMatrix has previously been used to calculate the inverse of a matrix, it will instead return the cached
## value of that matrix.

## makeCacheMatrix and cacheSolve are based on assignment provided functions makeVector and cachemean, the 
## implementation of which was not my work and is not being presented as my work.

## when called, makeCacheMatrix with matrix object "x". Initially sets the cached inverse, "i", 
## to NULL in the function environment.
## set allows a new matrix to be written into the function environment, resetting any cached "i" to NULL
## get holds the initial matrix "x" within the function environment.
## setinv holds the function needed to invert the matrix "x"
## getinv holds the value for i in the function environment
## finally, the function returns a list where each set or get component can be recalled by name.
        
makeCacheMatrix <- function(x = matrix()) {
                i <- NULL
                set <- function(y) {
                        x <<- y
                        i <<- NULL
                }
                get <- function() x 
                setinv <- function(solve) i <<- solve
                getinv <- function() i
                list(set = set, get = get,
                     setinv = setinv,
                     getinv = getinv)
        }


## cacheSolve first checks the object generated by makeCacheMatrix to see if there is already a cached inverse, "i" in 
## the function environment if there is a cached value for "i", cacheSolve returns the message "getting cached data" 
## followed by the previously
## computed value of "i"

## if "i" is null, then cacheSolve gets the input matrix held in makeCacheMatrix
## and determines its inverse with the solve() function, sets it as "i" and returns that value

cacheSolve <- function(x, ...) {
        i <- x$getinv()
        if(!is.null(i)) {
                message("getting cached data")
                return(i)
        }
        data <- x$get()
        i <- solve(data, ...)
        x$setinv(i)
        i       
        
         ## Returns a matrix that is the inverse of 'x'
}

## again, I'm not trying to pass off the original makeVector or cachemean function as my own work.